// Generated by CoffeeScript 1.12.4
var assertType, emptyFunction, index, listeners, tick;

emptyFunction = require("emptyFunction");

assertType = require("assertType");

module.exports = {
  addListener: function(listener) {
    assertType(listener, Function);
    listeners.push(listener);
    return listener;
  },
  removeListener: function(listener) {
    var position;
    assertType(listener, Function);
    position = listeners.indexOf(listener);
    if (position >= 0) {
      listeners.splice(position, 1);
    }
  }
};

index = -1;

listeners = [];

tick = function() {
  var length;
  if (length = listeners.length) {
    while (++index < length) {
      (listeners[index] || emptyFunction)();
    }
    index = -1;
  }
  requestAnimationFrame(tick);
};

requestAnimationFrame(tick);
